### ISSUE TITLE
tools>OpenAI>ChatGPT>URL Settings>Official>Login failed!

### ISSUE THREAD

**Issue by gaoxjin** [dromara/ChatGPT#104]
IntelliJ IDEA 2022.3.3 RC (Ultimate Edition)
tools>OpenAI>ChatGPT>URL Settings>Official>Login

Login failed!
Refresh access token failed, please try it later. Please check idea.log for more details

idea.log

2023-03-10 16:47:11,424 [ 956379]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.step5(OpenAIAuth.java:240)
2023-03-10 16:47:11,424 [ 956379]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.step4(OpenAIAuth.java:195)
2023-03-10 16:47:11,424 [ 956379]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.step3(OpenAIAuth.java:161)
2023-03-10 16:47:11,424 [ 956379]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.step2(OpenAIAuth.java:135)
2023-03-10 16:47:11,424 [ 956379]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.step1(OpenAIAuth.java:106)
2023-03-10 16:47:11,424 [ 956379]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.begin(OpenAIAuth.java:69)
2023-03-10 16:47:11,424 [ 956379]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.<init>(OpenAIAuth.java:43)
2023-03-10 16:47:11,425 [ 956380]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.<init>(OpenAIAuth.java:36)
2023-03-10 16:47:11,425 [ 956380]   INFO - STDERR - 	at com.obiscr.chatgpt.core.TokenManager.doRefreshToken(TokenManager.java:111)
2023-03-10 16:47:11,425 [ 956380]   INFO - STDERR - 	at com.obiscr.chatgpt.core.TokenManager$1.compute(TokenManager.java:71)
2023-03-10 16:47:11,425 [ 956380]   INFO - STDERR - 	at com.obiscr.chatgpt.core.TokenManager$1.compute(TokenManager.java:68)
2023-03-10 16:47:11,425 [ 956380]   INFO - STDERR - 	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:335)
2023-03-10 16:47:11,425 [ 956380]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
2023-03-10 16:47:11,425 [ 956380]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
2023-03-10 16:47:11,426 [ 956381]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:513)
2023-03-10 16:47:11,426 [ 956381]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
2023-03-10 16:47:11,426 [ 956381]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
2023-03-10 16:47:11,426 [ 956381]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
2023-03-10 16:47:11,426 [ 956381]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
2023-03-10 16:47:11,426 [ 956381]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
2023-03-10 16:47:11,426 [ 956381]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
2023-03-10 16:47:11,426 [ 956381]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
2023-03-10 16:47:11,426 [ 956381]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
2023-03-10 16:47:11,426 [ 956381]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
2023-03-10 16:47:11,426 [ 956381]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
2023-03-10 16:47:11,427 [ 956382]   INFO - STDERR - 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
2023-03-10 16:47:11,427 [ 956382]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-03-10 16:47:11,427 [ 956382]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-03-10 16:47:11,427 [ 956382]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
2023-03-10 16:47:11,427 [ 956382]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
2023-03-10 16:47:11,427 [ 956382]   INFO - STDERR - 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
2023-03-10 16:47:11,427 [ 956382]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
2023-03-10 16:47:11,427 [ 956382]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-10 16:47:11,723 [ 956678] SEVERE - com.obiscr.chatgpt.core.TokenManager - ChatGPT: Refresh access token failed, error = Get access token failed. Please try again later.

**Comment by obiscr** [comment]
Sorry, this is a problem with the third-party server, so we have to wait for the server maintainer to fix it.

A temporary alternative is to use Online ChatGPT.
