### ISSUE TITLE
Get Access Token Failed

### ISSUE THREAD

**Issue by imthaghost** [dromara/ChatGPT#109]
I constantly get the error message:

`ChatGPT: Refresh access token failed, error = Get access token failed. Please try again later.`
`OpenAIException{location='__part_five', statusCode=400, details='Your credentials are invalid.'}`

Yet I've copied and pasted my credentials exactly as they match.

**Comment by obiscr** [comment]
Hi，are you using a Google/Microsoft account?

**Comment by taoyang1223** [comment]
yes

**Comment by taoyang1223** [comment]
How to solve this problem

**Comment by obiscr** [comment]
Sorry, at the moment OpenAI does not officially support google/microsoft account login.

The recommended way is to login with another email account.（**No google/microsoft account**）

**Comment by taoyang1223** [comment]
2023-03-13 12:41:04,082 [268092425]   INFO - STDERR - OpenAIException{location='__part_six', statusCode=401, details='<html>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -   <head>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -     <meta charset="utf-8">
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -     <link href="https://cdn.auth0.com/styleguide/latest/index.min.css" rel="stylesheet" />
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -     <link rel="stylesheet" href="https://cdn.auth0.com/backend-templates/main.css">
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -     <meta name="viewport" content="width=device-width, initial-scale=1">
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -     <title>OpenAI</title>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -   </head>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -   <body>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -     <div class="unhandled-error-cont tenant-error-cont has-logo">
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -       <div class="error-header">
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -         <span class="error-icon">
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -           
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -           <span class="error-logo" style="background-image: url('https://openai.com/content/images/2019/05/openai-avatar.png');"></span>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -           
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -         </span>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -         <h3 class="error-title">OpenAI</h3>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -         
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -           <h3 class="error-subtitle">Oops!, something went wrong</h3>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -         
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -       </div>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -       <div class="error-body">
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -         <p class="error-message">
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -           
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -           You may have pressed the back button, refreshed during login, opened too many login dialogs, or there is some issue with cookies, since we couldn&#39;t find your session. Try logging in again from the application and if the problem persists please contact the administrator.
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -           
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -         </p>
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -       </div>
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -       <div class="error-footer">
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -         <div class="footer-groups cf">
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -           <span class="footer-group">
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -             <i class="footer-group-icon read-docs"></i>
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -             <h4 class="footer-group-title">TECHNICAL DETAILS</h4>
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -             <a href="#" class="toggle-details">See details for this error</a>
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -           </span>
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -           <span class="footer-group">
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -             <h4 class="footer-group-title">SUPPORT</h4>
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -             
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -               
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -               <a href="https://help.openai.com/" class="footer-group-link has-icon customer-support">Get Help</a>
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -               
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -               
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -               <a href="mailto:support@openai.com" class="footer-group-link has-icon mail">support@openai.com</a>
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -               
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -             
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -           </span>
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -         </div>
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -         <div class="error-details">
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -           <p class="error-status">
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -             
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -             <strong>access_denied</strong>: You may have pressed the back button, refreshed during login, opened too many login dialogs, or there is some issue with cookies, since we couldn&#39;t find your session. Try logging in again from the application and if the problem persists please contact the administrator.
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -             
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -           </p>
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -           
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -           <a href="https://manage.openai.auth0app.com/#/logs/" target="_new" class="view-logs-btn">VIEW LOG</a>
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -           
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR - 
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -           
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -           <span class="error-id">
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -             <span class="error-id-title">TRACKING ID: </span><span class="error-id-content">98156955d1ceea748000</span>
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -           </span>
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR -           
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR -         </div>
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR -       </div>
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR -     </div>
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR -     <script src="https://cdn.auth0.com/backend-templates/main.js?v=1"></script>
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR -   </body>
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR - </html>
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR - '}
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.step6(OpenAIAuth.java:264)
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.step5(OpenAIAuth.java:235)
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.step4(OpenAIAuth.java:195)
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.step3(OpenAIAuth.java:161)
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.step2(OpenAIAuth.java:135)
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.step1(OpenAIAuth.java:106)
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.begin(OpenAIAuth.java:69)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.<init>(OpenAIAuth.java:43)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.obiscr.chatgpt.core.TokenManager.doRefreshToken(TokenManager.java:103)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.obiscr.chatgpt.core.TokenManager$1.compute(TokenManager.java:71)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.obiscr.chatgpt.core.TokenManager$1.compute(TokenManager.java:68)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:335)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:526)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
2023-03-13 12:41:04,089 [268092432]   INFO - STDERR - 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
2023-03-13 12:41:04,089 [268092432]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
2023-03-13 12:41:04,089 [268092432]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-13 12:41:04,315 [268092658] SEVERE - c.o.c.c.TokenManager - ChatGPT: Refresh access token failed, error = Get access token failed. Please try again later.
My question is a bit different.

**Comment by taoyang1223** [comment]
> 2023-03-13 12:41:04,082 [268092425]   INFO - STDERR - OpenAIException{location='__part_six', statusCode=401, details='<html>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -   <head>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -     <meta charset="utf-8">
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -     <link href="https://cdn.auth0.com/styleguide/latest/index.min.css" rel="stylesheet" />
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -     <link rel="stylesheet" href="https://cdn.auth0.com/backend-templates/main.css">
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -     <meta name="viewport" content="width=device-width, initial-scale=1">
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -     <title>OpenAI</title>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -   </head>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -   <body>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -     <div class="unhandled-error-cont tenant-error-cont has-logo">
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -       <div class="error-header">
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -         <span class="error-icon">
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -           
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -           <span class="error-logo" style="background-image: url('https://openai.com/content/images/2019/05/openai-avatar.png');"></span>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -           
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -         </span>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -         <h3 class="error-title">OpenAI</h3>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -         
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -           <h3 class="error-subtitle">Oops!, something went wrong</h3>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -         
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -       </div>
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -       <div class="error-body">
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -         <p class="error-message">
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -           
2023-03-13 12:41:04,083 [268092426]   INFO - STDERR -           You may have pressed the back button, refreshed during login, opened too many login dialogs, or there is some issue with cookies, since we couldn&#39;t find your session. Try logging in again from the application and if the problem persists please contact the administrator.
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -           
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -         </p>
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -       </div>
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -       <div class="error-footer">
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -         <div class="footer-groups cf">
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -           <span class="footer-group">
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -             <i class="footer-group-icon read-docs"></i>
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -             <h4 class="footer-group-title">TECHNICAL DETAILS</h4>
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -             <a href="#" class="toggle-details">See details for this error</a>
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -           </span>
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -           <span class="footer-group">
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -             <h4 class="footer-group-title">SUPPORT</h4>
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -             
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -               
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -               <a href="https://help.openai.com/" class="footer-group-link has-icon customer-support">Get Help</a>
2023-03-13 12:41:04,084 [268092427]   INFO - STDERR -               
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -               
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -               <a href="mailto:support@openai.com" class="footer-group-link has-icon mail">support@openai.com</a>
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -               
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -             
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -           </span>
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -         </div>
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -         <div class="error-details">
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -           <p class="error-status">
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -             
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -             <strong>access_denied</strong>: You may have pressed the back button, refreshed during login, opened too many login dialogs, or there is some issue with cookies, since we couldn&#39;t find your session. Try logging in again from the application and if the problem persists please contact the administrator.
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -             
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -           </p>
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -           
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -           <a href="https://manage.openai.auth0app.com/#/logs/" target="_new" class="view-logs-btn">VIEW LOG</a>
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -           
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR - 
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -           
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -           <span class="error-id">
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -             <span class="error-id-title">TRACKING ID: </span><span class="error-id-content">98156955d1ceea748000</span>
2023-03-13 12:41:04,085 [268092428]   INFO - STDERR -           </span>
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR -           
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR -         </div>
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR -       </div>
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR -     </div>
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR -     <script src="https://cdn.auth0.com/backend-templates/main.js?v=1"></script>
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR -   </body>
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR - </html>
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR - '}
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.step6(OpenAIAuth.java:264)
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.step5(OpenAIAuth.java:235)
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.step4(OpenAIAuth.java:195)
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.step3(OpenAIAuth.java:161)
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.step2(OpenAIAuth.java:135)
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.step1(OpenAIAuth.java:106)
2023-03-13 12:41:04,086 [268092429]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.begin(OpenAIAuth.java:69)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.<init>(OpenAIAuth.java:43)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.obiscr.chatgpt.core.TokenManager.doRefreshToken(TokenManager.java:103)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.obiscr.chatgpt.core.TokenManager$1.compute(TokenManager.java:71)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.obiscr.chatgpt.core.TokenManager$1.compute(TokenManager.java:68)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:335)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:526)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
2023-03-13 12:41:04,087 [268092430]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
2023-03-13 12:41:04,088 [268092431]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
2023-03-13 12:41:04,089 [268092432]   INFO - STDERR - 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
2023-03-13 12:41:04,089 [268092432]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
2023-03-13 12:41:04,089 [268092432]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-13 12:41:04,315 [268092658] SEVERE - c.o.c.c.TokenManager - ChatGPT: Refresh access token failed, error = Get access token failed. Please try again later.

**Comment by obiscr** [comment]
I'm sorry about the solution to this problem. At the moment it can only be a few more attempts because the third party server is not stable.

But there is currently an update on the blocking situation, see here for details: https://github.com/dromara/ChatGPT/discussions/115

So it is not recommended to use ChatGPT built into the plugin, you can use GPT 3.5 Turbo or Online ChatGPT.
