### ISSUE TITLE
IllegalArgumentException when trying to send prompt in gpt Turbo tab.

### ISSUE THREAD

**Issue by wmitnaj** [dromara/ChatGPT#114]
I have configured my chatgpt API Key in the gpt turbo settings of the plugin with intellij 2022.3.3 and version 2.1.4-222.223 of this Plugin but I still get this when sending a prompt in the turbo tab:

java.lang.IllegalArgumentException: Width (-1) and height (-1) cannot be <= 0

                at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)

                at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:324)

                at cn.hutool.core.img.ImgUtil.copyImage(ImgUtil.java:1315)

                at cn.hutool.core.img.ImgUtil.copyImage(ImgUtil.java:1284)

                at cn.hutool.core.img.ImgUtil.toBufferedImage(ImgUtil.java:1181)

                at cn.hutool.core.img.Img.from(Img.java:136)

                at cn.hutool.core.img.ImgUtil.scale(ImgUtil.java:177)

                at com.obiscr.chatgpt.ui.MessageComponent.<init>(MessageComponent.java:59)

                at com.obiscr.chatgpt.core.SendAction.doActionPerformed(SendAction.java:108)

                at com.obiscr.chatgpt.ui.listener.SendListener.doActionPerformed(SendListener.java:33)

                at com.obiscr.chatgpt.ui.listener.SendListener.actionPerformed(SendListener.java:23)

                at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)

                at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)

                at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)

                at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)

                at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)

                at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)

                at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)

                at java.desktop/java.awt.Component.processEvent(Component.java:6413)

                at java.desktop/java.awt.Container.processEvent(Container.java:2266)

                at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)

                at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)

                at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)

                at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)

                at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)

                at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)

                at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)

                at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)

                at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)

                at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)

                at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)

                at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)

                at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)

                at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)

                at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)

                at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)

                at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)

                at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)

                at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)

                at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)

                at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)

                at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)

                at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)

                at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)

                at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)

                at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)

                at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)

                at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)

                at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)

                at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)

                at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)

                at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)

                at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)

                at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)

                at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)

                at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)

                at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

Any ideas what could be the problem? Is it a problem with a malformed answer or not getting an answer at all?

**Comment by obiscr** [comment]
This is a bug, it will be fixed in the next version

**Comment by wmitnaj** [comment]
Exactly, all I did was pasting my api key in the appropiate settings field under Tools > OpenAI > GPT 3.5 Turbo

**Comment by obiscr** [comment]
Does it always appear?

**Comment by obiscr** [comment]
The new version 2.1.5 is on its way to release. Can't make it in time to fix the problem this time. This problem will have to wait until the next update.

But what I can reveal is that this update supports disabling the avatar display. This should solve your problem for now.

**Comment by wmitnaj** [comment]
Thank you for the quick analysis of the bug. Looking forward to test out the new version.

**Comment by wmitnaj** [comment]
From where does the plugin get my avatar, is it the Avatar configured in openai?

**Comment by obiscr** [comment]
Yes, after you successfully log in via ChatGPT, the OpenAI server will return your avatar information URL, and the plugin will use this avatar.

Because you have not logged in before, there was a problem reading the avatar. Actually this has been done before. But it's strange, I don't know why this problem still occurs. I need to look into it more deeply. I may need your help later, thank you very much!

**Comment by wmitnaj** [comment]
After updating to the new version and disabling the avatar, everything works fine, thank you!

**Comment by obiscr** [comment]
You're welcome.

If you can, Please provide more information to help me solve this problem once and for all.

Search your computer for a file named: `ChatGPTSettingsPlugin.xml` , which is an xml file.

> There may be more than one, I want the file under the ide that won't work if you turn on the avatar.

Please find the line with `name="imageUrl"` and see what its value is.

**Note that this file contains information such as your accessToken, account number or password. Please do not share it with others. Do not post the contents of the file here either.**

I only need this line.

```xml
<option name="imageUrl" value="https://cdn.auth0.com/avatars/qb.png" />
```

Thank you!
