### ISSUE TITLE
can't login to Online ChatGPT

### ISSUE THREAD

**Issue by hagayj** [dromara/ChatGPT#130]
I'm stuck at the login/ signup window
the button "Log in" won't work
![image](https://user-images.githubusercontent.com/24786205/227877367-f40fe226-2e4b-43b1-805e-c212f616ca6a.png)

the plugin worked before good
I tried to uninstall and install it again
no luck

**Comment by obiscr** [comment]
This should be a network problem, or a problem with OpenAI's official website.

From the technical point of view, after the online Chat GPT page is loaded, all operations are hosted to the browser. The plug-in itself does not do any restrictions.

**Comment by hagayj** [comment]
I suggest another check
the network ok
with other browsers (outside pycharm), the Log in is working fine
it's ok i move to another plugin 

"termes of use / privacy policy " working good
the "log in  / Sign up" not responding

**Comment by hagayj** [comment]
when i press the button :
![image](https://user-images.githubusercontent.com/24786205/228351353-76ab0410-024a-4f7f-98ef-e2e47977c6bc.png)
and this is the error:
`java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.set(ArrayList.java:441)
	at com.obiscr.chatgpt.settings.CustomActionsPanel$3.setValue(CustomActionsPanel.java:93)
	at com.obiscr.chatgpt.settings.CustomActionsPanel$3.setValue(CustomActionsPanel.java:73)
	at com.intellij.util.ui.ListTableModel.setValue(ListTableModel.java:128)
	at com.intellij.util.ui.ListTableModel.setValueAt(ListTableModel.java:117)
	at com.intellij.util.ui.ListTableModel.setValueAt(ListTableModel.java:102)
	at java.desktop/javax.swing.JTable.setValueAt(JTable.java:2788)
	at java.desktop/javax.swing.JTable.editingStopped(JTable.java:4786)
	at java.desktop/javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:152)
	at java.desktop/javax.swing.DefaultCellEditor$EditorDelegate.stopCellEditing(DefaultCellEditor.java:375)
	at java.desktop/javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:234)
	at com.intellij.openapi.ui.cellvalidators.StatefulValidatingCellEditor.stopCellEditing(StatefulValidatingCellEditor.java:78)
	at com.intellij.ui.TableUtil.doRemoveSelectedItems(TableUtil.java:92)
	at com.intellij.ui.TableToolbarDecorator$4.run(TableToolbarDecorator.java:139)
	at com.intellij.ui.TableToolbarDecorator$4.run(TableToolbarDecorator.java:136)
	at com.intellij.ui.ToolbarDecorator$3.doRemove(ToolbarDecorator.java:605)
	at com.intellij.ui.CommonActionsPanel$RemoveButton.actionPerformed(CommonActionsPanel.java:373)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:197)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$0(ActionButton.java:176)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:350)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:176)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:465)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:743)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:467)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1676)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1634)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:134)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:107)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:99)
	at com.obiscr.chatgpt.ui.action.SettingAction.actionPerformed(SettingAction.java:22)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:197)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$0(ActionButton.java:176)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:350)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:176)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:465)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
`

**Comment by obiscr** [comment]
Can you give a complete description of your operation process? So that I can find the problem more accurately.

**Comment by krasa** [comment]
Clicked `Login` from settings:
![image](https://user-images.githubusercontent.com/1160875/228830388-06461494-c798-4c4f-8064-e1c720f48910.png)

```
2023-03-30 14:01:24,251 [78169650]   INFO - STDERR - cn.hutool.core.io.IORuntimeException: SSLHandshakeException: Received fatal alert: handshake_failure
2023-03-30 14:01:24,251 [78169650]   INFO - STDERR - 	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1304)
2023-03-30 14:01:24,251 [78169650]   INFO - STDERR - 	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1156)
2023-03-30 14:01:24,251 [78169650]   INFO - STDERR - 	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1030)
2023-03-30 14:01:24,251 [78169650]   INFO - STDERR - 	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1006)
2023-03-30 14:01:24,251 [78169650]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.begin(OpenAIAuth.java:65)
2023-03-30 14:01:24,251 [78169650]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.<init>(OpenAIAuth.java:43)
2023-03-30 14:01:24,251 [78169650]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.<init>(OpenAIAuth.java:36)
2023-03-30 14:01:24,251 [78169650]   INFO - STDERR - 	at com.obiscr.chatgpt.core.TokenManager.doRefreshToken(TokenManager.java:105)
2023-03-30 14:01:24,251 [78169650]   INFO - STDERR - 	at com.obiscr.chatgpt.core.TokenManager$1.compute(TokenManager.java:71)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at com.obiscr.chatgpt.core.TokenManager$1.compute(TokenManager.java:68)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:353)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:513)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
2023-03-30 14:01:24,252 [78169651]   INFO - STDERR - 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:358)
2023-03-30 14:01:24,253 [78169652]   INFO - STDERR - 	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
2023-03-30 14:01:24,253 [78169652]   INFO - STDERR - 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:204)
2023-03-30 14:01:24,253 [78169652]   INFO - STDERR - 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
2023-03-30 14:01:24,253 [78169652]   INFO - STDERR - 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
2023-03-30 14:01:24,253 [78169652]   INFO - STDERR - 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
2023-03-30 14:01:24,253 [78169652]   INFO - STDERR - 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
2023-03-30 14:01:24,253 [78169652]   INFO - STDERR - 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
2023-03-30 14:01:24,253 [78169652]   INFO - STDERR - 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
2023-03-30 14:01:24,253 [78169652]   INFO - STDERR - 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
2023-03-30 14:01:24,253 [78169652]   INFO - STDERR - 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
2023-03-30 14:01:24,253 [78169652]   INFO - STDERR - 	at cn.hutool.http.HttpConnection.connect(HttpConnection.java:384)
2023-03-30 14:01:24,253 [78169652]   INFO - STDERR - 	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1299)
2023-03-30 14:01:24,253 [78169652]   INFO - STDERR - 	... 31 more
2023-03-30 14:01:24,267 [78169666] SEVERE - com.obiscr.chatgpt.core.TokenManager - ChatGPT: Refresh access token failed, error = SSLHandshakeException: Received fatal alert: handshake_failure
```

**Comment by krasa** [comment]
Although I am not the author of this issue... :-)

**Comment by hagayj** [comment]
not a user error (that I know)
@obiscr on the top of the issue there is the problem description

**Comment by obiscr** [comment]
I read this error log and he has nothing to do with your problem.

I still can't reproduce your problem. Everything is working fine for me here. From experience, this is 90% a problem with your network.

Or you can try clicking on **×** on the toolbar to clear cookies to log in again.

**Comment by obiscr** [comment]
This issue is out of date.
