### ISSUE TITLE
SEVERE - c.o.c.c.TokenManager - ChatGPT: Refresh access token failed, error = ConnectException: Connection timed out: connect

### ISSUE THREAD

**Issue by LuoYuqi** [dromara/ChatGPT#156]
使用了vpn，网页版chatgpt可以正常登录
报错日志：
2023-04-01 19:57:07,284 [ 875380]   INFO - STDERR - cn.hutool.core.io.IORuntimeException: ConnectException: Connection timed out: connect
2023-04-01 19:57:07,284 [ 875380]   INFO - STDERR - 	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1304)
2023-04-01 19:57:07,284 [ 875380]   INFO - STDERR - 	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1156)
2023-04-01 19:57:07,284 [ 875380]   INFO - STDERR - 	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1030)
2023-04-01 19:57:07,284 [ 875380]   INFO - STDERR - 	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1006)
2023-04-01 19:57:07,284 [ 875380]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.begin(OpenAIAuth.java:65)
2023-04-01 19:57:07,285 [ 875381]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.<init>(OpenAIAuth.java:43)
2023-04-01 19:57:07,285 [ 875381]   INFO - STDERR - 	at com.obiscr.OpenAIAuth.<init>(OpenAIAuth.java:36)
2023-04-01 19:57:07,285 [ 875381]   INFO - STDERR - 	at com.obiscr.chatgpt.core.TokenManager.doRefreshToken(TokenManager.java:105)
2023-04-01 19:57:07,285 [ 875381]   INFO - STDERR - 	at com.obiscr.chatgpt.core.TokenManager$1.compute(TokenManager.java:71)
2023-04-01 19:57:07,285 [ 875381]   INFO - STDERR - 	at com.obiscr.chatgpt.core.TokenManager$1.compute(TokenManager.java:68)
2023-04-01 19:57:07,285 [ 875381]   INFO - STDERR - 	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:335)
2023-04-01 19:57:07,285 [ 875381]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
2023-04-01 19:57:07,285 [ 875381]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
2023-04-01 19:57:07,285 [ 875381]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:526)
2023-04-01 19:57:07,285 [ 875381]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:83)
2023-04-01 19:57:07,285 [ 875381]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
2023-04-01 19:57:07,285 [ 875381]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
2023-04-01 19:57:07,286 [ 875382]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
2023-04-01 19:57:07,286 [ 875382]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
2023-04-01 19:57:07,286 [ 875382]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
2023-04-01 19:57:07,286 [ 875382]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
2023-04-01 19:57:07,286 [ 875382]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
2023-04-01 19:57:07,286 [ 875382]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
2023-04-01 19:57:07,286 [ 875382]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
2023-04-01 19:57:07,286 [ 875382]   INFO - STDERR - 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
2023-04-01 19:57:07,286 [ 875382]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-04-01 19:57:07,286 [ 875382]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-04-01 19:57:07,286 [ 875382]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
2023-04-01 19:57:07,286 [ 875382]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
2023-04-01 19:57:07,287 [ 875383]   INFO - STDERR - 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2023-04-01 19:57:07,287 [ 875383]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
2023-04-01 19:57:07,287 [ 875383]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:829)
2023-04-01 19:57:07,287 [ 875383]   INFO - STDERR - Caused by: java.net.ConnectException: Connection timed out: connect
2023-04-01 19:57:07,287 [ 875383]   INFO - STDERR - 	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
2023-04-01 19:57:07,287 [ 875383]   INFO - STDERR - 	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
2023-04-01 19:57:07,287 [ 875383]   INFO - STDERR - 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
2023-04-01 19:57:07,287 [ 875383]   INFO - STDERR - 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
2023-04-01 19:57:07,287 [ 875383]   INFO - STDERR - 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
2023-04-01 19:57:07,287 [ 875383]   INFO - STDERR - 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
2023-04-01 19:57:07,287 [ 875383]   INFO - STDERR - 	at java.base/java.net.Socket.connect(Socket.java:609)
2023-04-01 19:57:07,288 [ 875384]   INFO - STDERR - 	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:305)
2023-04-01 19:57:07,288 [ 875384]   INFO - STDERR - 	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
2023-04-01 19:57:07,288 [ 875384]   INFO - STDERR - 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
2023-04-01 19:57:07,288 [ 875384]   INFO - STDERR - 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
2023-04-01 19:57:07,288 [ 875384]   INFO - STDERR - 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
2023-04-01 19:57:07,288 [ 875384]   INFO - STDERR - 	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
2023-04-01 19:57:07,288 [ 875384]   INFO - STDERR - 	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
2023-04-01 19:57:07,288 [ 875384]   INFO - STDERR - 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
2023-04-01 19:57:07,288 [ 875384]   INFO - STDERR - 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
2023-04-01 19:57:07,288 [ 875384]   INFO - STDERR - 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
2023-04-01 19:57:07,288 [ 875384]   INFO - STDERR - 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
2023-04-01 19:57:07,288 [ 875384]   INFO - STDERR - 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
2023-04-01 19:57:07,288 [ 875384]   INFO - STDERR - 	at cn.hutool.http.HttpConnection.connect(HttpConnection.java:384)
2023-04-01 19:57:07,289 [ 875385]   INFO - STDERR - 	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1299)
2023-04-01 19:57:07,289 [ 875385]   INFO - STDERR - 	... 31 more
2023-04-01 19:57:28,333 [ 896429] SEVERE - c.o.c.c.TokenManager - ChatGPT: Refresh access token failed, error = ConnectException: Connection timed out: connect

**Comment by obiscr** [comment]
This problem is same as https://github.com/dromara/ChatGPT/issues/150, it's all because fo the thiry party server. I am on fix it.
For further developments, please follow #150

**Comment by JiangYutang-Y** [comment]
使用GPT-3.5-Turbo,一直提示这个错误Response failure, cause: Connect timed out, please try again.Tips: if proxy is enabled, please check if the proxy server is working.，我用的是梯子是[FLY IN GBIRD]，用v2rayN连接的，也在setting -> GPT-3.5-Turbo中设置了manual proxy，是我设置错误了吗？

**Comment by JiangYutang-Y** [comment]
API KEY也是自己生成了正确的，就是连接不了用不了GPT-3.5-Turbo

**Comment by obiscr** [comment]
如果配置正确，GPT-3.5-Turbo应该是可以正常工作的。
